version: '2'

services:
  dw-php7: 
    build: ./build
    ports:
      - "8080:80"
    volumes:
      - ./workdir:/var/www/html/dw/
      - ./config/php.conf:/usr/local/etc/php/conf.d/php.ini:ro
    environment:
      MYSQL_HOST: dw-mysql
      MYSQL_DATABASE: dw
      MYSQL_USER: dw
      MYSQL_PASSWORD: abcdef
      ILIAS_URL: https://ilias.test.cat.internal/
      ILIAS_MASTER_PASSWORD: abcdef
      ILIAS_RELEASE: release_5-2
    links:
      - dw-mysql

  dw-mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: abcdef
      MYSQL_DATABASE: dw
      MYSQL_USER: dw
      MYSQL_PASSWORD: abcdef

  dw-myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: dw-mysql
